version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      timezone: "Asia/Kolkata"
    groups:
      next-core:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "eslint*"
          - "@next/*"
          - "typescript"
        update-types:
          - minor
          - patch
          - major
      tooling:
        patterns:
          - "@types/*"
          - "prettier*"
          - "lint*"
          - "eslint-*"
          - "vitest*"
          - "jest*"
          - "ts-*"
          - "*config*"
        update-types:
          - minor
          - patch
          - major
      all-others:
        patterns:
          - "*"
        exclude-patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@next/*"
        update-types:
          - minor
          - patch
          - major
      security-batch:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
