"use client";

import { motion } from "motion/react";
import { ArrowRightIcon } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function NotFound() {
  return (
      <main className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden bg-gradient-to-b from-gray-950 via-slate-900 to-black text-center text-white">
            {/* 🌠 Planet glow in background */}
                  <div className="absolute inset-0 -z-10">
                          <div className="absolute top-1/2 left-1/2 h-[50rem] w-[50rem] -translate-x-1/2 -translate-y-1/2 rounded-full bg-gradient-to-tr from-purple-700/30 via-pink-600/20 to-blue-500/10 blur-[160px]" />
                                </div>

                                      {/* ✨ Floating animated stars */}
                                            <div className="absolute inset-0 -z-10 overflow-hidden">
                                                    {[...Array(30)].map((_, i) => (
                                                              <motion.div
                                                                          key={i}
                                                                                      className="absolute bg-white/40 rounded-full"
                                                                                                  style={{
                                                                                                                width: Math.random() * 3 + 1 + "px",
                                                                                                                              height: Math.random() * 3 + 1 + "px",
                                                                                                                                            top: Math.random() * 100 + "%",
                                                                                                                                                          left: Math.random() * 100 + "%",
                                                                                                                                                                      }}
                                                                                                                                                                                  animate={{
                                                                                                                                                                                                y: [0, -30, 0],
                                                                                                                                                                                                              opacity: [0.6, 1, 0.6],
                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                      transition={{
                                                                                                                                                                                                                                                    duration: 3 + Math.random() * 2,
                                                                                                                                                                                                                                                                  repeat: Infinity,
                                                                                                                                                                                                                                                                                delay: Math.random() * 2,
                                                                                                                                                                                                                                                                                              ease: "easeInOut",
                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                        {/* 🧑‍🚀 Floating Astronaut */}
                                                                                                                                                                                                                                                                                                                                              <motion.div
                                                                                                                                                                                                                                                                                                                                                      initial={{ y: 30, opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                              animate={{ y: [0, -10, 0], opacity: 1 }}
                                                                                                                                                                                                                                                                                                                                                                      transition={{
                                                                                                                                                                                                                                                                                                                                                                                duration: 4,
                                                                                                                                                                                                                                                                                                                                                                                          repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                                                    ease: "easeInOut",
                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                    className="absolute -top-24 sm:-top-16 right-[15%] sm:right-[25%] z-10"
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg
                                                                                                                                                                                                                                                                                                                                                                                                                                            xmlns="http://www.w3.org/2000/svg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      viewBox="0 0 120 120"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                fill="none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="h-28 w-28 opacity-80"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <circle cx="60" cy="60" r="58" stroke="white" strokeOpacity="0.1" strokeWidth="1.5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  d="M59 40c6 0 10 5 10 10v5c0 5-4 9-9 9h-2c-5 0-9-4-9-9v-5c0-5 4-10 10-10Z"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              stroke="white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          strokeWidth="2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <circle cx="59" cy="50" r="3" fill="white" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    d="M50 64c-6 3-10 8-10 15 0 2 1 4 3 4h34c2 0 3-2 3-4 0-7-4-12-10-15M59 64v17"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                stroke="white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            strokeWidth="2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            d="M35 80c-5 3-7 7-5 10s8 3 12-2M83 80c5 3 7 7 5 10s-8 3-12-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stroke="white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    strokeOpacity="0.6"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                strokeWidth="1.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* 🌈 Animated Gradient “404” */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.h1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initial={{ y: 40, opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={{ y: [0, -15, 0], opacity: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      duration: 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ease: "easeInOut",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-[8rem] sm:text-[10rem] font-extrabold bg-gradient-to-r from-cyan-400 via-purple-500 to-pink-500 bg-clip-text text-transparent select-none animate-gradient"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        404
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* 💬 Subtitle */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, y: 10 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          animate={{ opacity: 1, y: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition={{ delay: 0.6 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mt-4 mb-10 max-w-md text-gray-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Lost in space? The page you’re looking for drifted away from the galaxy.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* 🪐 Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, scale: 0.9 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          animate={{ opacity: 1, scale: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition={{ delay: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button asChild className="bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-400 hover:to-blue-400 shadow-lg shadow-purple-900/30">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/" className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Return Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ArrowRightIcon className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }