name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate-build:
    runs-on: ubuntu-latest
    
        with:
          fetch-depth: 0

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: '25'
          check-latest: true
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
