name: Init Next.js

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  create_next_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "25"


      - name: Install chosen package manager
        run: |
          PM="pnpm"
          if [ "$PM" = "pnpm" ]; then
            corepack enable
            corepack prepare pnpm@latest --activate
          elif [ "$PM" = "yarn" ]; then
            corepack enable
            corepack prepare yarn@stable --activate
          elif [ "$PM" = "bun" ]; then
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> $GITHUB_PATH
          fi

      - name: Build Next.js Site
        run: |
          pnpm run build

      - name: lint and fix code
        if: success()
        run: |
          pnpm lint --fix

      